### ISSUE TITLE
Dependency installation error

### ISSUE THREAD

**Issue by mshreevatsa** [tdeekens/flopflip#1040]
**Describe the bug**
Packages are not installed after you clone

**Version:**
npm: `6.14.2`
node: `v12.14.1`
macos: Catalina 10.15.4

Due to un-maintained dependency:
https://www.npmjs.com/package/rollup-plugin-commonjs

It should be changed to: `@rollup/plugin-commonjs`

**To Reproduce**
npm install after clone

**Expected behavior**
It should install all the dependency packages successfully

**Comment by tdeekens** [comment]
Thanks for reporting. I opened a PR.

**Comment by mshreevatsa** [comment]
Can we test this externally like a separate project? A demo with example would be helpful
