### ISSUE TITLE
A lot of babel dependecies are failing to install

### ISSUE THREAD

**Issue by mshreevatsa** [tdeekens/flopflip#1042]
**Describe the bug**
Installation Error:

```
17 http fetch GET 304 https://registry.npmjs.org/@babel%2fplugin-proposal-object-rest-spread 197ms (from cache)
18 http fetch GET 304 https://registry.npmjs.org/@babel%2fplugin-proposal-export-default-from 203ms (from cache)
19 http fetch GET 304 https://registry.npmjs.org/@babel%2fplugin-external-helpers 205ms (from cache)
20 http fetch GET 304 https://registry.npmjs.org/@babel%2fplugin-proposal-nullish-coalescing-operator 203ms (from cache)
21 http fetch GET 304 https://registry.npmjs.org/@babel%2fplugin-proposal-class-properties 208ms (from cache)
```

**To Reproduce**
npm install

1. Given '...'
2. Then '....'
3. That '....'

**Expected behavior**
It should install successfully and demo should be working

**Screenshots**

**Additional context**

**Comment by tdeekens** [comment]
Thanks. Will try on my end. Not sure what I can do about it. Will update them and see what that does.

**Comment by tdeekens** [comment]
I tried locally and didn't get the 304. Can you try again on your end while pulling master? Thanks.

**Comment by tdeekens** [comment]
Also CI can't reproduce it. Please re-open if it still persists. Thanks!
