### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by thomassvensen** [tdeekens/flopflip#1057]
I am doing an upgrade of the packages in our solution, and I see that there has been many new versions of Flopflip, including a major upgrade from 9 to 10. But I struggle to understand what has been changed for me as a user of this library, are there any breaking changes? Are there new features?

It would be really useful if the releases included some hints about what has changed / is new, like e.g. AppInsights does: https://github.com/microsoft/ApplicationInsights-JS/releases

Thank you for providing a useful library!

**Comment by tdeekens** [comment]
Yes, I know I should be more careful. It's hard to know when to do them and when not. I did them in the past and was never sure if anybody in the world cares. Then I stopped doing them to save some time and use it in the code. 

What's the range you jump from to. Then I can this time just point out what the chagnes are :)

**Comment by thomassvensen** [comment]
I understand your dilemma, but I would care very much 😉

Currently, this is the jump:
@flopflip/launchdarkly-adapter     2.9.1   -->  2.13.2                        
@flopflip/react-redux              9.1.0   -->  10.1.14

**Comment by tdeekens** [comment]
There are release notes for the critical part of the version ranges. It's all semver for so the adapter there is nothing to worry about. 

https://github.com/tdeekens/flopflip/releases?after=%40flopflip%2Freact-broadcast%4010.1.1

It's only about the needed react version. Given you have that installed you should be able to just update both :)

**Comment by thomassvensen** [comment]
Great! Thank you for the confirmation that nothing big has changed.
