### ISSUE TITLE
Warning from launchdarkly adapter

### ISSUE THREAD

**Issue by thomassvensen** [tdeekens/flopflip#1058]
I have now upgrade both flopflip and the LD adapter to the latest version and it seems to work fine, but we are getting a lot of these in our console log:

```
react_devtools_backend.js:6 Warning: @flopflip/launchdarkly-adapter: `getIsReady` has been deprecated. Please use `getIsConfigurationStatus` instead. 
    in ConfigureAdapter (created by ConfigureFlopflip)
    in ConfigureFlopflip (at src/​index.js:29)
```

Seems like the LD adapter needs to be updated?

**Comment by tdeekens** [comment]
Not really. The older version of the adapters had a `getIsReady`. Never version have a `getIsConfigurationStatus` which is more flexible. This API is used by the Configure component in @flopflip/react to communicate with the underlying adapter. The @flopflip/react package is a dependency of the @flopflip/react-broadcast and @flopflip/react-redux packages. I presume you have an outdated @flopflip/react-broadcast or @flopflip/react-redux and as a result an outdated @flopflip/react talking to the adapter using the deprecated API. It's generally not a problem but it would be worthwhile to update all packages at the same time.

**Comment by thomassvensen** [comment]
I have updated both the latest versions:
```
    "@flopflip/launchdarkly-adapter": "2.13.2",
    "@flopflip/react-redux": "10.1.4",
```
It only happens on my dev machine, though, not when running the prod build on the test server.

**Comment by tdeekens** [comment]
That's likely cause the warning from `tiny-warning` is bundled away. I will then have to check this. Thanks for reporting!

**Comment by thomassvensen** [comment]
Hi, any update on this? Our console log is filled with these warnings, so would be nice to avoid this, if possible.

**Comment by tdeekens** [comment]
I have failed to reproduce it. Can you maybe share a Codesandbox for the issue?

**Comment by thomassvensen** [comment]
It does not happen in a code sandbox: https://codesandbox.io/s/bold-sutherland-gwr7g?file=/src/index.js

But it happens on our dev machines:
![image](https://user-images.githubusercontent.com/77299/80197185-9aa70780-861e-11ea-969e-aff5bc5beba0.png)

which refers to this line:

![image](https://user-images.githubusercontent.com/77299/80197314-c2966b00-861e-11ea-806c-2fcf29bdc090.png)

Does that give any useful hint?

**Comment by tdeekens** [comment]
Ok. Cause I double checked the code. On recent versions this method is not invoked anymore.

Can you run

```bash
yarn why @flopflip/launchdarkly-adapter
yarn why @flopflip/react-redux
```

and share the output?

**Comment by thomassvensen** [comment]
```
07:04:55 ~/dev/ -  (master) $ yarn why @flopflip/launchdarkly-adapter
yarn why v1.22.4
[1/4] 🤔  Why do we have the module "@flopflip/launchdarkly-adapter"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "@flopflip/launchdarkly-adapter@2.13.2"
info Has been hoisted to "@flopflip/launchdarkly-adapter"
info This module exists because it's specified in "dependencies".
info Disk size without dependencies: "116KB"
info Disk size with unique dependencies: "6.4MB"
info Disk size with transitive dependencies: "7.18MB"
info Number of shared dependencies: 14
✨  Done in 1.40s.
12:08:35 ~/dev -  (master) $ yarn why @flopflip/react-redux
yarn why v1.22.4
[1/4] 🤔  Why do we have the module "@flopflip/react-redux"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "@flopflip/react-redux@10.1.4"
info Has been hoisted to "@flopflip/react-redux"
info This module exists because it's specified in "dependencies".
info Disk size without dependencies: "1.08MB"
info Disk size with unique dependencies: "7.1MB"
info Disk size with transitive dependencies: "9.54MB"
info Number of shared dependencies: 14
✨  Done in 1.12s.
```

**Comment by tdeekens** [comment]
Thanks. The relevant lines are

```
=> Found "@flopflip/launchdarkly-adapter@2.13.2"
=> Found "@flopflip/react-redux@10.1.4"
```

Can you try to use `@flopflip/react-redux@10.1.14`?

**Comment by thomassvensen** [comment]
Ah, I am truly sorry for mixing up `1.4` with `1.14`! I just read the wrong time after time. Thank you very much for your patience and helpfulness! ❤️

**Comment by tdeekens** [comment]
@thomassvensen the release process has dramatically improved via changesets. All is nicely documented now. https://github.com/tdeekens/flopflip/releases

**Comment by thomassvensen** [comment]
Nice, much appreciated! 👍 @tdeekens
