### ISSUE TITLE
createFlopFlipEnhancer not working

### ISSUE THREAD

**Issue by robinmakinson** [tdeekens/flopflip#131]
Was trying to use createFlopFlipEnhancer in the app I'm working on and in the flopflip demo too. 
The following error is showing up and am wondering why? 

Unhandled promise rejection (rejection id: 79): Error: Actions must be plain objects. Use custom middleware for async actions.

**Comment by tdeekens** [comment]
Sorry to hear that. I will have a look. To be fair we have not used it as a store enhancer for a long time and I just kept it around. Feel free to dig around. I am thankful for clues.

**Comment by tdeekens** [comment]
I am curious now though as to what made you decide using the store enhancer over the ConfigureFlopFlip component?

**Comment by tdeekens** [comment]
[This](https://github.com/tdeekens/flopflip/pull/141) closes the issue. I've tested it in the demo with the local-storage adapter and everything works fine again. I will release this soon. Thanks for reporting!

**Comment by tdeekens** [comment]
https://github.com/tdeekens/flopflip/releases/tag/%40flopflip%2Freact-redux%405.1.5
