### ISSUE TITLE
Unable to launch demo

### ISSUE THREAD

**Issue by lrabiet** [tdeekens/flopflip#1418]
**Describe the bug**
I get a compilation error for missing tsconfig.json file. 

**To Reproduce**
I did the following
1. From the repositories root: yarn build:watch
2. From /demo: first yarn and then yarn start

**Expected behavior**
A working webpage

**Screenshots**
<img width="993" alt="Screenshot 2021-03-03 at 20 16 00" src="https://user-images.githubusercontent.com/1489464/109859533-5da79a80-7c5d-11eb-87f2-1df1b21ee19b.png">

**Additional context**

**Comment by tdeekens** [comment]
Sorry about that. Haven't used the demo in ages. Would you mind looking into it?
