### ISSUE TITLE
Inconsistency between documentation to code 

### ISSUE THREAD

**Issue by shayco37** [tdeekens/flopflip#147]
For example:
In readme.md appears:

```js
export default branchOnFeatureToggle({
  flag: flagsNames.THE_FEATURE_TOGGLE,
  variation: 'variate1',
})(ComponentToBeToggled, ComponentToBeRenderedInstead);
```

**instead** variation must be variate according to code.

Also appears:

```js
export default branchOnFeatureToggle({ flag: flagsNames.THE_FEATURE_TOGGLE })(
  ComponentToBeToggled,
  ComponentToBeRenderedInstead
);
```
**while** the correct code is:

```js
export default branchOnFeatureToggle(
{ flag: flagsNames.THE_FEATURE_TOGGLE }, ComponentToBeRenderedInstead)(
  ComponentToBeToggled
);
```

**Comment by tdeekens** [comment]
Thanks for reporting this. I will look into it, update the readme accordingly and close it from a PR.

**Comment by tdeekens** [comment]
I think your absolutely right about the glitch in the usage of `branchOnFeatureToggle`. Thanks again for reporting. The second issue regarding `variate` over `variations`: it was `variate` in the beginning of the library. Then other users proposed to have it named `variation`. So maybe you're on an older version. I checked the code again too [here](https://github.com/tdeekens/flopflip/blob/master/packages/react-redux/modules/components/branch-on-feature-toggle/branch-on-feature-toggle.js#L14). Hope I got that right.

**Comment by tdeekens** [comment]
Please verify is the `readme.md` now is what you'd expect and close the issue depending on it.

**Comment by shayco37** [comment]
I guess you are correct regarding the 'variation', I'm using react-redux@4.2.0, that must be it.

**Comment by tdeekens** [comment]
Yeah, [these](https://github.com/tdeekens/flopflip/releases/tag/%40flopflip%2Freact%405.0.3) are the release notes from the 5.0.0 release containing a list of the breaking changes.
