### ISSUE TITLE
Cannot statically analyse `require(…, …)` caused by old version of `clone-deep`.

### ISSUE THREAD

**Issue by emmenko** [tdeekens/flopflip#1609]
> Opening an issue for reference, in case someone else is having the same problem.

**Describe the bug**

Getting an error when building an application with Webpack.

```
Cannot statically analyse 'require(…, …)' in line 11
```

**Screenshots**

<img width="661" alt="image" src="https://user-images.githubusercontent.com/1110551/160554855-180d1f25-c62c-47f7-8570-d4f7379028ad.png">

**Additional context**

The `merge-deep` package uses an [old `clone-deep` dependency](https://github.com/jonschlinkert/merge-deep/pull/14) which causes the above error. Updating `clone-deep` to its latest version `v4` fixes the isse.

More info here: https://github.com/tdeekens/flopflip/commit/4f13cb85167d33e89d03aeaba2d991f2a9f0728c#r69821886

**Comment by tdeekens** [comment]
Thanks. Will try to use https://github.com/voodoocreation/ts-deepmerge.

It's a bit of a dance with dependencies as the prior library had a non-defined dependency https://github.com/TehShrike/deepmerge/issues/245.

**Comment by tdeekens** [comment]
The releases in [this PR](https://github.com/tdeekens/flopflip/pull/1611) could fix the issue. Let me know if it does and if so feel free to close the issue :-).

**Comment by tdeekens** [comment]
I think this was fixed. Please re-open if I am wrong :)
