### ISSUE TITLE
Next.js bug with React 18

### ISSUE THREAD

**Issue by vcapretz** [tdeekens/flopflip#1658]
**Describe the bug**

I'm updating Next.js and React packages to latest, as well as `@flopflip/` ones and I started getting the following error:

<img width="962" alt="CleanShot 2022-08-25 at 15 36 09@2x" src="https://user-images.githubusercontent.com/14620121/186742660-b8d25752-b5c7-4f3b-bcb4-906f802ab47d.png">

Here are my package versions for reference: 

```
"@flopflip/launchdarkly-adapter": "5.0.29",
"@flopflip/react-broadcast": "12.3.1",
"next": "12.2.5",
"react": "18.2.0",
"react-dom": "18.2.0",
```

I tracked a similar issue on Google and people reported the same issue with the `zustand` lib, the fix on their end: https://github.com/pmndrs/zustand/commit/5a0b404fe7c3ac509636c62b47aa9182c4bddd12

original issue: https://github.com/pmndrs/zustand/issues/886

**To Reproduce**

have a Next.js project with React 18 and have your app wrapped in a `ConfigureFlopFlip` adapter

**Comment by tdeekens** [comment]
Thanks for reporting the issue. I've personally not used the library in Next.js but it's a great idea. Would you be open to contribute a fix as a PR?

**Comment by vcapretz** [comment]
Yep @tdeekens! I'll get to it and send a PR 😄

**Comment by vcapretz** [comment]
@tdeekens feel free to review when you have some time! maybe I missed some unintentional consequences, let me know!

**Comment by tdeekens** [comment]
Thanks. I think we can just give it a shot.
