### ISSUE TITLE
ts-deepmerge v3 generates Source Map warnings

### ISSUE THREAD

**Issue by aaronmcdavid** [tdeekens/flopflip#1676]
**Describe the bug**
@flopflip/react and @flopflip/react-redux rely on ts-deepmerge 3.0.0.  This version generates a build warning when using create-react-app v5.x.  ts-deepmerge v4.0.0 fixes the warning.  Please update the appropriate package.json files to use the new version.

**Additional context**
See [Issue 19](https://github.com/voodoocreation/ts-deepmerge/issues/19) at ts-deepmerge.

**Comment by tdeekens** [comment]
Thanks. Will publish a version with updated ts-deepmerge today.

**Comment by tdeekens** [comment]
Published.
