### ISSUE TITLE
Usage in Typescript files causes TS3205

### ISSUE THREAD

**Issue by trisrael** [tdeekens/flopflip#243]
Things were working great with the library, then a teammate translated a file into TypeScript and this error started occurring.

`account_page.tsx(8,10): error TS2305: Module ''@flopflip/react-broadcast'' has no exported member 'ToggleFeature'.`

I figure this is an issue with not seeing the typings associated with FlopFlip or, worse, it can not understand the directory structure of @flopflip/react|react-broadcast in its resolution.

We have `moduleResolution: 'node'` in our `tsconfig.json`.

I've attempted a few things so far, such as changing `typeRoots` in `tsconfig.json` to additionally have the paths to the `/types` directories in react/react-broadcast respectively, but this has not worked.

Any ideas?

**Comment by trisrael** [comment]
Looks like it's related to lacking a `module` in our `compilerOptions` in tsconfig.json

Found this StackOverflow
https://stackoverflow.com/questions/41861948/typescript-module-has-no-exported-member

and tried setting my `module: 'system'` which made that issue go away.... so closing.

**Comment by trisrael** [comment]
Okay... so the actual fix was to 
`npm install @flopflip/types --save`


I figured this out after some time and looking at the type definitions in react-broadcast.
I managed to remove @flopflip/types somehow which is a peer dependency and used in typings.

```
declare module '@flopflip/react-broadcast' {
  export * from '@flopflip/types';
}
```

**Comment by tdeekens** [comment]
> Things were working great with the library

Great to hear. Thanks for sticking to it!

> npm install @flopflip/types --save

I literally wrote TypeScript bindings for my own learning purposes. If you have any suggestions of ways of improving things I really appreciate guidance or even a PR.
The idea behind the "reexport" was to have shared typing behind the counterparts of the library to that is "easy" to maintain.

**Comment by trisrael** [comment]
Okay, yeah. I'm not great at TS, new to it myself.
I did find some bugs in the implementation that I can open a PR for.

Where can I find how to build/test the packages?

Ideally, I like developing using `npm link @flopflip/types` but I'm not sure how I would do so with the nested.
