### ISSUE TITLE
[RFC]: Add `ReconfigureFlopflip` component

### ISSUE THREAD

**Issue by tdeekens** [tdeekens/flopflip#277]
> There might be a case for a `ReconfigureFlopflip` component for this library.

### Introduction

Flopflip is generally configured by `ConfigureFloplip` by passing an `adapter`, `adapterArgs` among other things. Depending on the underlying adapter the user context can change. This is handled automatically by the `launchdarkly-adapter` as of late. Whenever any of the user props change the underlying adapter will reconfigure through `ConfigureFlopflip`. This may yield a new set of flags depending on your flag configuration.

### Case for the addition

A project or mine has a setup in which `ConfigureFlopflip` is rendered very high up the tree. Some of the user properties however as part of the `adapterArgs` are only known further down the component tree. This is instance can hold for any project with RR4 where a `<Route>` quite low in the tree. Imagine anything of that `match` prop should end up in the `user` of `adapterArgs`. You're stuck having to pass down an quite imperative setter function e.g. `setProjectKey` which somehow sideways changes the user context. If this is possible depends on the adapter. The `ldAdapter` exposes a `changeUserContext` which shallowly merges in any new passed props of a `nextUser`. This might seem doable at first but is not really declarative.

The same could be solved by a `ReconfigureFlopflip` which only receives e.g. two props `nextAdapterArgs` and a `exact` prop (defaulting to `false`). Depending on if `exact` is `true` the `nextAdapterArgs` are shallowly merged or overwritten.

### Example

```jsx
<Route
    exact={false}
    path="/:projectKey"
    render={routerProps => (
       <React.Fragment>
           <MyRouteComponent />
           <ReconfigureFlopflip exact={false} adapterArgs={{ projectKey: routerProps.projectKey }} />
       </React.Fragment>
    )}
/>
```

### Changes required

1. Adding the `ReconfigureFlopflip` component itself
2. The `ConfigureFlopflip` has to pass the adapter (or only `reconfigure`) onto the context of flopflip
3. Potentially use `calculateChangeBits` for the flags and `reconfigure` on the context to subscribe to only needed context state

**Comment by emmenko** [comment]
I like the declarative component! ❤️ It makes it much easier to use and leaves the implementation details hidden within flopflip.

I haven’t quite got the reason for having the `exact` prop but the idea of the component is very good! Thanks for looking into this 🙏

**Comment by tdeekens** [comment]
The exact prop is only as I thought there might be cases where you 1. want to add something (maybe a single attribute) to the user and 2. there may be cases where you want to overwrite the user with a given set if props completely. Maybe the name is confusing. We can change that late into a PR though.

**Comment by emmenko** [comment]
Ah ok, got it. Yeah, it's just an implementation detail.

**Comment by tdeekens** [comment]
Went for a walk to think about this. Let's give it a swing. I thought of other things this has to cover

1. Lift the `create-react-context` dependency up to `@flopflip/react`
   - It will put both `flags` and the `adapter` onto the context
   - Use `calculateChangedBits` to allow consumers to subscribe to only relevant parts
2. Rework `ConfigureFlopflip` and `ConfigureAdapter` a bit as responsibilities will shift

An alternative would be to use the "old" (buhar) context API. But I saw on a PR of Andrew that they plan to deprecate it maybe in 16.4 already. I think React@17 will be a quite major cleanup version for them.
