### ISSUE TITLE
`shouldDeferAdapterConfiguration` not working as intended

### ISSUE THREAD

**Issue by Kerumen** [tdeekens/flopflip#324]
I have an issue with `shouldDeferAdapterConfiguration` in my app. I'll try to explain it: I have an XHR call which populate a user. So I set `shouldDeferAdapterConfiguration={!user.key}` and flopflip should not initialize until my user is ready. This is not the case. I investigated and maybe I found why.

First the component `ConfigureFlopFlip` mount and this condition match so the adapter is not configured. Good behaviour.
https://github.com/tdeekens/flopflip/blob/60d023c7c42efad54d9d0249dabb89d16cf1289f/packages/react/modules/components/configure-adapter/configure-adapter.js#L140

Then, when my user is ready, `componentWillReceiveProps` is called with `this.reconfigureOrQueue`.
https://github.com/tdeekens/flopflip/blob/60d023c7c42efad54d9d0249dabb89d16cf1289f/packages/react/modules/components/configure-adapter/configure-adapter.js#L133

The adapter is not yet configured so `setPendingAdapterArgs` is called
https://github.com/tdeekens/flopflip/blob/60d023c7c42efad54d9d0249dabb89d16cf1289f/packages/react/modules/components/configure-adapter/configure-adapter.js#L87

My new user lives now in `this.pendingAdapterArgs` ready to be passed to the adapter but `applyPendingAdapterArgs` is never called
https://github.com/tdeekens/flopflip/blob/60d023c7c42efad54d9d0249dabb89d16cf1289f/packages/react/modules/components/configure-adapter/configure-adapter.js#L105

`componentDidUpdate` occurs and now, `this.props.shouldDeferAdapterConfiguration` is `false` so `configure` is called, however `this.state.appliedAdapterArgs` doesn't have my user. So an error is triggered LaunchDarkly side.
https://github.com/tdeekens/flopflip/blob/60d023c7c42efad54d9d0249dabb89d16cf1289f/packages/react/modules/components/configure-adapter/configure-adapter.js#L166

I don't have enough visibility on the code yet to provide a fix. Let me know if any information can help :)

**Comment by tdeekens** [comment]
Thanks for the detailed description. I'll try to have a look this weekend. Sorry for the inconvenience!

**Comment by tdeekens** [comment]
I think the problem "just" lies in not having considered that when the adapter was not configured yet that 1. we need to after also "flush" the pending adapter args with a `this.applyPendingAdapterArgs();`. Same we do when the adapter is configured on a call to `componentDidUpdate`. With is dangerous as it will trigger a `setState` from the `componentDidUpdate` which might end up in a setState loop. Option 2. would entail to just configure the adapter on the first run with merged adapter args (pending and applied). Will think about it some more.

**Comment by tdeekens** [comment]
Forgive me. Forgot to add a "closes" to the PR.
