### ISSUE TITLE
UPDATE_FLAGS & UPDATE_STATUS action types are no longer exposed on ver. 5.1.0

### ISSUE THREAD

**Issue by shayco37** [tdeekens/flopflip#401]
UPDATE_FLAGS and UPDATE_STATUS action types used to be exposed on ver. 4.x.x and now they don't. I've used those two items to sync between several react applications while initialize launch darkly only once in one of those application but duplication actions values by putting it on a sort of publish/subscribers sort of solution. I would appreciate if you could expose it again instead of me creating a constant holding those values.

**Comment by tdeekens** [comment]
Sure. Sorry about that. Did not anticipate them to be used. I will get to it as soon as I can.

**Comment by shayco37** [comment]
Thanks 👍

**Comment by tdeekens** [comment]
PR is up. I didn't rename the action types to something like `FLOPFLIP_UPDATE_FLAGS` as I tink consumers can do that in `import { UPDATE_FLAGS as FLOPFLIP_UPDATE_FLAGS } from '@flopflip/react-redux` if needed.

**Comment by tdeekens** [comment]
Releases as `6.1.1`.
