### ISSUE TITLE
TypeScript definitions not accurate

### ISSUE THREAD

**Issue by 18steps** [tdeekens/flopflip#414]
**Actual behavior:**

`dist/index/typings/index.d.ts` does not export e.g. `createFlipFlopEnhancer`, but `@flopflip-react-redux.es.js` does. 

So when importing in an IDE like e.g. WebStorm, the import shows as unresolved, because it checks the definitions file.

**Desired behavior:**
Type definitions include all exports exposed by `es.js` files, so they show as resolved imports in IDEs.

**Comment by omichelsen** [comment]
Here's a list of the missing exports:

- createFlopFlipEnhancer
- FLOPFLIP_STATE_SLICE
- createFlopflipReducer
- flopflipReducer
- selectFeatureFlags
- selectFeatureFlag
- UPDATE_STATUS
- UPDATE_FLAGS
- version

**Comment by tdeekens** [comment]
Cool thanks a bunch. So is somebody open to add these or is it me?

**Comment by omichelsen** [comment]
I can give it a go...

**Comment by tdeekens** [comment]
Thanks for the effort. Just asking to clarify if the TypeScript definitions are now complete or good enough. I'll close the issue assuming that they are. Feel free to re-open if there is work for me/us.
