### ISSUE TITLE
Switch from create-react-context to React 16 context API?

### ISSUE THREAD

**Issue by AndrewRayCode** [tdeekens/flopflip#472]
I was investigating how the non-redux version works, and found you use [`create-react-context`](https://github.com/jamiebuilds/create-react-context) - should this be replaced with the new context API?

Also, for what it's worth, it was pretty confusing the non-redux package is called react-broadcast, for which there is already an [npm package](https://www.npmjs.com/package/react-broadcast) that has the same purpose as replacing the context api. I was looking for a while where react-broadcast was used, couldn't find it, and got more confused trying to figure out where context is coming from since there were no calls to `createContext`

**Comment by tdeekens** [comment]
The initial version used `react-broadcast` as a broadcasting mechanism. I then moved to create-react-context which ponyfills the react context. So when you're on react 16 you will use the "native" new context api. I don't plan on changing the broadcasting package's name. The initial idea was to clearly distinguish the redux and broadcasting mechanism variants.

**Comment by tdeekens** [comment]
Eventually, in a breaking release some day I could also rename the package to `react-context` but I wonder if that's so much less confusing and causes more "pain" than it solves good.
