### ISSUE TITLE
Loading state not exposed to app

### ISSUE THREAD

**Issue by AndrewRayCode** [tdeekens/flopflip#473]
It would be nice if a `loading` prop was available either as a function as child argument, so that consumers could opt in to not rendering their apps until the connection to launch darkly has succeeded (or failed)

**Comment by tdeekens** [comment]
True, there might be a use case for that. I guess you would want that exposed through `<ConfigureAdapter>`? Would you want to give it a try to implement?

**Comment by tdeekens** [comment]
I like this idea. To be sure I fully understand this. We would provide two component APIs for `ConfigureAdapter`:

1. The "normal" way which just drops in the React.Node
   - Just like `ToggleFeature`
2. The "new" way which goes for FaaC and a render-prop
   - Just like `ToggleFeature`

```jsx
// like before
<ConfigureAdapter adapterArgs={...} adapter={...}>
  <div />
</ConfigureAdapter>

// with FaC
<ConfigureAdapter adapterArgs={...} adapter={...}>
   // Internally it's called isReady as it's not a pull based
   // model for most adapters but a socket
   {{ isReady } => isReady ? <div /> : <LoadingSpinner />}
</ConfigureAdapter>

// with render prop same as ToggleFeature (and e.g. react-router) only called when actually ready
<ConfigureAdapter adapterArgs={...} adapter={...} render={() => <div />}/>
```

Would this solve your needs?

**Comment by AndrewRayCode** [comment]
yup I used a fac for loading for another component in the same domain and it worked well. my worry was the breaking change and was thinking you could do a runtime type check of children, but breaking change to always do it looks good to me

**Comment by tdeekens** [comment]
Please check the PR. It‘s a non breaking change checking children/render. It‘s analogous to ToggleFeature which creates familiarity. I don‘t think everybody needs it.
