### ISSUE TITLE
Add option to not live update from feature flagging upstream

### ISSUE THREAD

**Issue by AndrewRayCode** [tdeekens/flopflip#474]
We have some mission critical workflows where we don't want the UI to live shift out from under our users. It would be nice to have the option to disable a live subscription to the flagging system.

I could probably hack around this with a HOC wrapper holding a `<ConfigureFlopFlip />` that only passes the initial flag load down to components, but it would be nice to have this first class.

**Comment by tdeekens** [comment]
To be honest I don't know if that should leak into the library. One of the core ideas was to have real time feature toggles and not "lock them into" their initial state. It could be an option passed to the adapter which then does not invoke the `onFlagsStateChange` callbacks. I've to think about this a bit.

**Comment by tdeekens** [comment]
Thinking about this a bit. If we go with this it should probably be called `shouldListenToFlagUpdates` which defaults to `true`. I don't like props defaulting to false like `shouldIgnoreFlagUpdates` as they often lead to poor component design. 

I am mostly wondering "why the UI changes underneath your users". Is it that somebody plays with e.g. the LaunchDarkly dashboard? Is that then really an issue the library should attempt to solve? If nobody "messes" or updates flags then the UI will not shift underneath the users?

This thought kind of makes me lean towards not adding it as it's still kind of against the whole goal of the library with an attaching a real time toggling adapter like LaunchDarkly.

**Comment by AndrewRayCode** [comment]
It seems like the code is opting in to the feature of the launchdarkly SDK, it's not a requirement of using the SDK. We have customers using our product 24/7 and there's no "safe" time to turn on a flag. I'd rather have the UI different on a new page load than to have the UI move while someone could be using it

**Comment by tdeekens** [comment]
Please refer to #479 if this is what you intended.
