### ISSUE TITLE
Allow reset of memory-adapter

### ISSUE THREAD

**Issue by dferber90** [tdeekens/flopflip#475]
First of all: Lovely package :)

I'm using the `memory-adapter` in an integration test to provide the default flags like this:

```jsx
import memoryAdapter from '@flopflip/memory-adapter'

<ConfigureFlopFlip
  adapter={memoryAdapter}
  defaultFlags={{ someFeature: true }}
>
  <ComponentUnderTestWhichUsesFlags />
</ConfigureFlopFlip>
```

It would be great if it was possible to reset the `memoryAdapter` after each test like so

```js
afterEach(() => {
  memoryAdapter.reset()
})
```

Do you think this is a good idea?

The closest thing to this I've found would be to do `memoryAdapter.reconfigure()`. Or should we have a dedicated `test-adapter`?

**Comment by tdeekens** [comment]
Reset on an adapter would be good. Could also work for all adapters as I‘d like all to have the samd API. The only concern is that the defaultFlags would go onto the adaperState and serve as the basis for a reset. Nothing too bad just how it could work I suppose. 

This reset would mostly be for testing, right? I‘ve heard people also demanding a locked-in adapter. Essentially not updating it‘s flags after it received them initially. Not related but something which I‘d like to maybe to in one release.

**Comment by tdeekens** [comment]
I think you would need to have an onChange on the adapter to trigger the change handlers passed by ConfigureAdapter. You expose reset on the adapter which internally onChanges to the defaultFlags. Might need some shifting of code to make it easier to follow.

**Comment by dferber90** [comment]
Thanks for going forward with this! I'm looking at the feature request purely from a consumer perspective wanting to write tests.

An alternative to having a `reset` method would be to turn the adapter into a factory. Then we wouldn't need the reset at all.

Then the tests could be:

```js
import createMemoryAdapter from '@flopflip/memory-adapter'

describe('ComponentUnderTestWhichUsesFlags', () => {
  it('should render "hello" when someFeature is on', () => {
    const memoryAdapter = createMemoryAdapter()
    const { getByText } = render(
      <ConfigureFlopFlip
        adapter={memoryAdapter}
        defaultFlags={{ someFeature: true }}
      >
        <ComponentUnderTestWhichUsesFlags />
      </ConfigureFlopFlip>
    )
    expect(getByText('Hello')).toBeVisible();
  })
  it('should not render "hello" when someFeature is off', () => {
    const memoryAdapter = createMemoryAdapter()
    const { queryByText } = render(
      <ConfigureFlopFlip
        adapter={memoryAdapter}
        defaultFlags={{ someFeature: false }}
      >
        <ComponentUnderTestWhichUsesFlags />
      </ConfigureFlopFlip>
    )
    expect(queryByText('Hello')).toBeNull();
  })
})
```

The following API would work as well (for tests at least):

```js
describe('ComponentUnderTestWhichUsesFlags', () => {
  it('should render "hello" when someFeature is on', () => {
    const memoryAdapter = createMemoryAdapter({ someFeature: true })
    const { getByText } = render(
      <ConfigureFlopFlip adapter={memoryAdapter}>
        <ComponentUnderTestWhichUsesFlags />
      </ConfigureFlopFlip>
    )
    expect(getByText('Hello')).toBeVisible();
  })
  it('should not render "hello" when someFeature is off', () => {
    const memoryAdapter = createMemoryAdapter({ someFeature: false })
    const { queryByText } = render(
      <ConfigureFlopFlip adapter={memoryAdapter}>
        <ComponentUnderTestWhichUsesFlags />
      </ConfigureFlopFlip>
    )
    expect(queryByText('Hello')).toBeNull();
  })
})
```

I guess the factory would then also have to provide the `updateFlags` and `getUser` methods on the adapter?  So either

```js
const adapter = createMemoryAdapter()
// adapter.getUser(); adapter.updateFlags(); adapter.configure(); adapter.reconfigure();

// or
const { adapter, updateFlags, getUser } = createMemoryAdapter()
```

To me the first one is clearer, as it's the adapter giving us the user and handling the flag update.

**Comment by dferber90** [comment]
Sounds good to me as well 👍
