### ISSUE TITLE
TS2306: File 'typings/index.d.ts' is not a module

### ISSUE THREAD

**Issue by joshua-mbg** [tdeekens/flopflip#493]
I've cloned the current repo and ran the build. I'm linking my current project to the cloned flopflip repo. My webpack project is throwing the following error with tslint

```bash
ERROR in /projectDir/src/components/CopyTranscript/CopyTranscript.tsx
./src/components/CopyTranscript/CopyTranscript.tsx
[tsl] ERROR in /projectDir/src/components/CopyTranscript/CopyTranscript.tsx(1,31)
      TS2306: File '/projectDir/node_modules/flopflip/packages/react-redux/dist/typings/index.d.ts' is not a module.
```

**Comment by tdeekens** [comment]
Thanks for the issue! Sorry for the slightly delayed response, busy days.

I just ran build on `master` to check if the file was copied correctly to `dist/typings` and for me it is. Can you verify if the file exists in your working directory in the dist folder?

**Comment by tdeekens** [comment]
@joshua-mbg any update from your side here? Anyway I can help?
