### ISSUE TITLE
Named exports in @flopflip/react-broadcast ?

### ISSUE THREAD

**Issue by Eightyplus** [tdeekens/flopflip#574]
**Describe the bug**
According to the [Readme](https://github.com/tdeekens/flopflip#flopflipreact-redux--flopflipreact-broadcast-api) (as I read it), `ConfigureFlopFlip` and `injectFeatureToggles ` are available through `@flipflot/react-broadcast`

Basically I would like to
`import { ConfigureFlopFlip } from '@flopflip/react-broadcast';` and
`import { injectFeatureToggles } from '@flopflip/react-broadcast';`
but it does not work.

**Comment by Eightyplus** [comment]
Wow that was a fast reply, thanks. I'll have to looking to the module loader I guess.

**Comment by tdeekens** [comment]
Sure. Gotten anywhere? Need help? What bundler are you using? This is what points a bundler in the right direction: https://github.com/tdeekens/flopflip/blob/master/packages/react-broadcast/package.json#L5-L7

**Comment by Eightyplus** [comment]
Trying to take weekend off 😊
I don’t know if it that easy to change the bundler. All our apps are using create-react-pp as standard, and we’re not suppose to change the Webpack config. 
I’ll take a look at it on Monday.

**Comment by Eightyplus** [comment]
Ok, turns out WebStorm is not so happy about it, but create-react-app/react-scripts handles it just fine. I was using `injectFeatureToggles` wrong, which led me to a wrong conclusion. My bad. 

Webstorm import:
<img width="446" alt="screenshot 2019-01-30 at 09 02 20" src="https://user-images.githubusercontent.com/15194982/51966785-c3693d00-246d-11e9-9953-e29989eacd13.png">

When I toggle a flag on launch darkly, the change does not take effekt before I reload the page. Is it possible to configure this to be without reload, or is this a feature request?

**Comment by tdeekens** [comment]
This should work and does for me/us. The LD adapter sets up a socket to keep flags updated automatically. You can always check the latest flags in flopflip on the flags prop of the ConfigureFlopflip component. You can also check the network so see if the flag change is sent. Maybe your targeting is setup so that you are not affected by the change. I will check later if I can reproduce the issue. Thanks.

**Comment by Eightyplus** [comment]
I see it works, maybe the updates were delayed since I was testing while commuting. 

Thanks for the help!
