### ISSUE TITLE
launchdarkly-adapter is not creating the right user

### ISSUE THREAD

**Issue by Kerumen** [tdeekens/flopflip#62]
There is an issue, I guess due to the recent refactoring.
In all the adapters the configure signature is:

https://github.com/tdeekens/flopflip/blob/f857c86464c6d21528c40941d0d8451156296516/packages/localstorage-adapter/modules/adapter/adapter.js#L31-L37

Whereas in the `launchdarkly-adapter` you spread the user arg (since this commit https://github.com/tdeekens/flopflip/commit/4998b88fe50765cd51a920e684709e26efe5d13c):

https://github.com/tdeekens/flopflip/blob/f857c86464c6d21528c40941d0d8451156296516/packages/launchdarkly-adapter/modules/adapter/adapter.js#L84-L90

This doesn't respect the API as `adapterArgs` should take an `user` key, not a spreaded key.

So there is a change that have to be made. I can PR the change but I want to open the issue first for the discussion. Should I fix the adapter and re-accept a `user` key in the `configure` signature (not spreaded) or when the `FlagsSubscription ` component call `.configure()`, spread the user key?

Let me know!

**Comment by tdeekens** [comment]
🎈 Wooh, thanks for contributing and caring about this project! 👍 

This definitely smells a bit like an unintended heterogeneity between the adapters and their APIs. Cool that you opened an issue to discuss things first.

I see two solutions to the "issue".

1. "Scope" the `user` on the `launchdarkly-adapter` onto a user property and not spread it
   - which is what you prefer from what I understand
2. Assume that user data is in the `remainingArgs` in other adapters too (as `userArgs` is that just named differently)
3. Spreading the user in the FlagsSubscrption
  - Sounds a big off as it feels like a leaky abstraction to me.
 
Solution 1. would be a breaking change for the `launchdarkly-adapter` which is fine just something to be aware of. It would also remove the need of `remainingArgs` on all adapters as none needs a spread of remaining/rest args.

You're preference would be solution 1, correct?

**Comment by Kerumen** [comment]
Yes, solution 1 is the best for me and follows the initial API (as described in the README for `configure`).
It's true that it will be a breaking change, buuut nobody reported it and it doesn't work as it should do.

**Comment by tdeekens** [comment]
Yeah, totally agree. I can fix that over the weekend releasing the changed adapter if thats fine by you.

**Comment by Kerumen** [comment]
Yup! That would be cool! 👍🏻

**Comment by tdeekens** [comment]
Feel free to review and leave comments if you like https://github.com/tdeekens/flopflip/pull/63. If not also totally fine. I intend to release some time later this weekend.

**Comment by tdeekens** [comment]
I interpret that 👍 on the PR as a review passed? 😄

**Comment by tdeekens** [comment]
Should be closed with https://github.com/tdeekens/flopflip/releases/tag/%40flopflip%2Flaunchdarkly-adapter%402.0.0

Let me know if there is anything else.

**Comment by Kerumen** [comment]
@tdeekens Yes! Sorry I was unavailable this week-end. It works perfectly, thanks for the update 😃

**Comment by tdeekens** [comment]
Sure, no worries. Glad I was of help and even cooler that you use the library!
