### ISSUE TITLE
`ready` event is emitted on error when initializing client

### ISSUE THREAD

**Issue by gnerkus** [tdeekens/flopflip#679]
**Is your feature request related to a problem? Please describe.**

A `LaunchDarklyFlagFetchError` is sometimes thrown during client initialization. This seems to occur because the `ready` event gets emitted as soon as the initialization logic has finished, regardless of whether it succeeded as explained here: https://github.com/launchdarkly/js-client-sdk/issues/113#issuecomment-422123189

**Describe the solution you'd like**

The `ready` event is only emitted on successful initialization

**Describe alternatives you've considered**

The `waitUntilReady` method call here
https://github.com/tdeekens/flopflip/blob/9537bd28d54f384f53e99907b05e3897bb50ff2e/packages/launchdarkly-adapter/modules/adapter/adapter.ts#L151
could be replaced with the `waitForInitialization` method as discussed here:
https://github.com/launchdarkly/js-client-sdk/issues/113#issuecomment-424922537

**Comment by tdeekens** [comment]
Awesome. Thanks for letting me know this exists. Wasn't aware.
