### ISSUE TITLE
Change the flopflip reducer key

### ISSUE THREAD

**Issue by Kerumen** [tdeekens/flopflip#68]
Currently, the flopflip reducer key is defined as `@flopflip`. It's a problem if you want to destructure your state (in a `connect()` for example) because you get a parsing error due to the `@`.

```js
connect(({ @flopflip, user, .. }) => ({
  ...
}))
```

Maybe change the key to simply `flopflip` would be better.

**Comment by tdeekens** [comment]
Internally it doesn‘t make a difference to change the key. However I‘d currently see it as internal to the library almost (even if it‘s nit really). However if one starts using it, changing it becomes a breaking thing. Maybe it should be configurable instead onlx defaulting to the @flilflop. 

However why do you want to use/extract flags from the store. Generally this is what I envisioned injectFeatureToggle(s) for. So you would compose connect and injectFeatureToggle.

**Comment by Kerumen** [comment]
Yes but when your component is already connected, it seems tedious to add a `compose` and an `injectFeatureToggle` only to get one flag. But it's the way `redux-form` works so I think we should keep it this way.

And for the name, it's up to you. I think a simple name like `flopflip` would be better (as `redux-form` has `form`).

**Comment by tdeekens** [comment]
Yeah maybe the name could be changed true. It's a bit aligned to the app I am working on right now which composes things (the redux-form way kinda) into components.

**Comment by tdeekens** [comment]
Thinking about this a little. I've drafted a refactoring of the internal constants [here](https://github.com/tdeekens/flopflip/compare/fix/state-slice-and-constants). Just to make sure we're on the same page. However, I started to wonder why you don't import the `FLOPFLIP_STATE_SLICE` constant which I exposed planned to expose for such a case (also for the setup in a redux app ([ref](https://github.com/tdeekens/flopflip/blob/2811bc0e12ddd6648d74f1a57e78a451b8fdc1a4/packages/react-redux/modules/index.js#L3)).

```js

const mapStateToProps = state => ({
   isFeatureOn: state[FLOPFLIP_STATE_SLICE].flags.someRandomFeature
})

connect(mapStateToProps)(FooComponent)
```

The same "thing" happens in the library [here](https://github.com/tdeekens/flopflip/blob/master/packages/react-redux/modules/components/inject-feature-toggle/inject-feature-toggle.js#L7).

However, I feel that this is not really "idiomatic" as you loose out of one or two things of what the library tries to offer e.g. [this](https://github.com/tdeekens/flopflip/blob/master/packages/react/modules/components/inject-feature-toggle/inject-feature-toggle.js#L11). It should in anyway fit your use case if I am not mistaken.

**Comment by tdeekens** [comment]
What we instead should probably do, as it encapsulates data access, is to expose a selector. So that others can import a ˋselectFeatureFlagˋ.

**Comment by tdeekens** [comment]
Will be closed by the feature above.

**Comment by tdeekens** [comment]
Voila https://github.com/tdeekens/flopflip/releases/tag/%40flopflip%2Freact-redux%404.1.0

More here: https://github.com/tdeekens/flopflip#flopflipreact-redux-additional-api--exports

Thanks for the suggestion, hoping that this does this trick. Closed the issue with a PR `closes`. If it's not what you were after feel free to reopen.

**Comment by tdeekens** [comment]
Please refer to https://github.com/tdeekens/flopflip/releases/tag/%40flopflip%2Freact-redux%404.1.1. After some reflection and integration I felt this "emergency" fix (even though breaking) makes sense before it's used in the wild 🦆.

**Comment by Kerumen** [comment]
Yes it's nice! It works clearly better this way. Thanks :)
