### ISSUE TITLE
splitio-adapter: reconfigure does not work

### ISSUE THREAD

**Issue by jaypea** [tdeekens/flopflip#689]
**Describe the bug**
I was trying to configure flopflip with react-redux and  splitio-adapter in the described way.
1. use `createFlopFlipEnhancer` when creating the store. although there is no user-context available during store creation in my app. 
2. during app bootstrap or after login: call reconfigure on the adapter with the users key and details

the reconfigure method in https://github.com/tdeekens/flopflip/blob/master/packages/splitio-adapter/modules/adapter/adapter.ts#L192
does not change the user key and user config in the splitio client objects. 

The splitio client itself does not provide an option to change the user key or user details besides configuring a new client.

this is what i do as a workaround, call `configure` instead of `reconfigure` in my redux actions after login. downside of this is, that i have to maintain some extra state to determine if the user has changed and i cannot use the `createFlopFlipEnhancer`

**Comment by tdeekens** [comment]
The splitio-adapter was written by @Kerumen. I am not sure if he uses it himself still. 

The `createFlopFlipEnhancer` itself is not really "good" at deferring the initialisation. The `ConfigureFlopflip` however has a `shouldDeferAdapterConfiguration` which I use exactly for the described login scenario where configuration should only occur post login.

**Comment by jaypea** [comment]
if i understand the code correctly, using `shouldDeferAdapterConfiguration` would not call `configure` on the adapter but only `reconfigure`. this would break with the splitio-adapter as well since the reconfigure method does not work at all.

**Comment by tdeekens** [comment]
It would defer calling `configure` until `shouldDeferAdapterConfiguration` is `true`.

1. If the adapter has been configured before it would then call reconfigure
2. It the adatper has not yet been configured it would call configure

**Comment by tdeekens** [comment]
Published:

Successfully published:
 - @flopflip/react-redux@8.1.3
 - @flopflip/splitio-adapter@1.3.14

Thanks a lot for your contributions!

**Comment by Kerumen** [comment]
Hello 🙂

We switched to LaunchDarkly so yes, I don't use it anymore sorry!
