### ISSUE TITLE
Launch Darkly Goals

### ISSUE THREAD

**Issue by zslabs** [tdeekens/flopflip#713]
**Describe the bug**
When using [Launch Darkly A/B tests](https://docs.launchdarkly.com/docs/running-ab-tests), I am passing through the `fetchGoals` to `clientOptions`, but I'm not sure if my click targets are actually being populated back to LD; as there service also mentions adding the following to start tracking goals:

```js
ldClient.track("your-goal-key", user);
```

If this is something FlopFlip doesn't do by default, would I have access to the client and user to be able to load that?

**Expected behavior**
Successful clicks should talk back to LD for the goal.

**Comment by tdeekens** [comment]
Sorry for the late response. I've personally not used goals yet. Given you'd have to report back the tracking of the goals I would say we just add that to the `launchdarkly-adapter` and maybe not expose the complete underlying client (cause then any breaking change update to the client will be a breaking adapter update) but a little wrapped API to track goals. What do you think?

**Comment by zslabs** [comment]
👋 @tdeekens thanks for the response! I've been in contact with their support, and from what I've been told, the `fetchGoals` parameter "should" be doing the job of what the `track()` method I mentioned above does manually, so I'm wondering if we need to do much here at all. I say this with the caveat that I haven't been able to get the goal click listeners (the type of goal I have setup) to actually talk back to LD; so this one is a bit of a mystery while I work this out with their support.

In the event you happen to come across anything of value that their support may be missing - that's awesome! Otherwise, I'll report back with my findings.

**Comment by zslabs** [comment]
Working as expected; there was a bug on Launch Darkly's side that they finally fixed. All is well, thanks as always @tdeekens !

**Comment by zslabs** [comment]
Ah - forgot I had opened up this question previously as well (related to https://github.com/tdeekens/flopflip/issues/829)
