### ISSUE TITLE
isAdapterReady does not mean "flag is ready"

### ISSUE THREAD

**Issue by zslabs** [tdeekens/flopflip#753]
**Describe the bug**
👋 I've run into a bit of a roadblock where `isAdapterReady` (or using the `useAdapterStatus` hook) does not necessarily imply that `useFeatureToggle` is actually ready at the same time from LaunchDarkly. I'm using FlopFlip to directly impact whether a page is available to load - or if a user should be redirected to the homepage. This feels like a bit of a race-condition that I'm having some trouble getting around and wanted to see if you had any thoughts. Thanks!

**To Reproduce**

```
const featureEnabled = useFeatureToggle('feature')

  const { isReady } = useAdapterStatus()

  if (!isReady) {
    return <div>loading</div>
  } else if (!featureEnabled) {
    return <Redirect to="/" />
  }

  return <div>page stuff</div>
```

**Expected behavior**
Show loading at first, then show "page stuff" as feature flag is verified to be available.

**Comment by tdeekens** [comment]
Thanks for reporting. 

I have myself only used the adapter status one and it when I implemented it. The isReady state is set and flushed right before flags. https://github.com/tdeekens/flopflip/blob/master/packages/launchdarkly-adapter/modules/adapter/adapter.ts

I assume your expectation would be that it would be flushed after all flags are fetched?

Upon first thought this makes sense and also is what I was after. I can not recall why it didn‘t also lead to race conditions for me. Maybe because it triggered too fast after one another.

**Comment by zslabs** [comment]
@tdeekens Appreciate the quick reply! Yes, my ideal would be if they were available straight-away. 

I notice the "blip" in content changes which are normally fine to deal with, but when attempting to feature flag a route (or entire page render) this is where I ended up going down the route of trying a `useEffect` hook onMount which only seemed to reaffirm the potential race-condition there as it occasionally did work.

Would certainly be interested in the flags being available, as that could potentially fix the "blip" in content toggles as well.

**Comment by tdeekens** [comment]
Yeah, it makes sense. I think it's also what I would expect reflecting on the feature again. I will try to have a look at this soon. If you want to look into it yourself and change the order of events being emitted: PRs are always welcome.

**Comment by tdeekens** [comment]
Fix is released. It's within the adapter. You can try if this does the trick for you with `@flopflip/launchdarkly-adapter@2.7.1`.

**Comment by zslabs** [comment]
This works great! Thank you very much for taking a look at this so quickly; I really appreciate it!

**Comment by tdeekens** [comment]
Thanks for reaching out and improving things.
