### ISSUE TITLE
`onlyUpdateForKeys` is not working as expected

### ISSUE THREAD

**Issue by Kerumen** [tdeekens/flopflip#77]
I didn't understand well what `onlyUpdateForKeys` did and it seems is not solving the case I had. Even worse, it introduces a bug.. 😞 

I see 2 issues: first, you call `onlyUpdateForKeys` on `flagNames`. But the component won't have a prop named `flagNames`. It will have a prop `propKey`. So I think the comparison have to be on this.

https://github.com/tdeekens/flopflip/blob/d2ef336dd2da965ecf8bd01191208a78a09b58f1/packages/react/modules/components/inject-feature-toggles/inject-feature-toggles.js#L21

Second, my component can have other props. So if I update these props, it won't rerender. This is very problematic.

I'm investigating on my app how to solve these issues.

**Comment by tdeekens** [comment]
Thanks. Lets test these things better next time then.

**Comment by tdeekens** [comment]
I unpublished the broken version and removed the releases. This should really be a canary release on a next channel next time. This should not happen again.

**Comment by Kerumen** [comment]
Yes, I agree. Sorry for the trouble, I wasn't sure about the `onlyUpdateForKeys` thing.
Next time, I'll try to test all the PR on my app.

**Comment by tdeekens** [comment]
Also from my side sorry. I almost did a canary release with `lerna` to @next but then it publishes every package and I wasn't too sure about doing that.

**Comment by Kerumen** [comment]
@tdeekens Okay I tested in my app. I found something.

I changed the `onlyUpdateForKeys` in `compose(` with a `shouldUpdate` and comparing the `props[propKey]` with `nextProps[propKey]` (with a deep compare) and it works!
It also rerender my component if its props change (other than the `featureToggles` flag).
We can try this way I guess :)

**Comment by tdeekens** [comment]
That's odd. Cause `onlyUpdateForKeys` actually uses `shouldUpdate`. See [ref](https://github.com/acdlite/recompose/blob/master/src/packages/recompose/onlyUpdateForKeys.js).

**Comment by Kerumen** [comment]
Yes but it's a shallow equal. When we pick `props[propKey]` (`this.props.featureToggles` in the app), it's an object. And `{} !== {}` so a shallow compare won't work here. We must deep compare each flags values.
Another solution would be to flatten the flags, shallow compare and "unflatten".

**Comment by tdeekens** [comment]
Ah thanks. I generally thing that `onlyUpdateForKeys` was a bad-ish idea as it also restricts the consumer component to re-render on other `props` which might be super unintended. I will try to spin up a sandbox to experiment with things.

**Comment by tdeekens** [comment]
After some thought and fiddling I think the only way to get the right is to be careful

- Using `onlyUpdateForKeys` or `shouldUpdate` might yield in to much render avoidances for consumers
    - Imagine you export that component, pass in an unrelated flag which changes put the component won't re-render as the flags haven't chaned
- Comparing first flags and on change re-render while then taking into account any other props also feels odd but might be an option for later optimization. I've not heard of people actually using `injectFeatureToggles` most use `injectFeatureToggle` further down the tree.

Anyway. I added a `shallowlyCompareFlags` to `injectFeatureToggles` as the last argument which defaults to `false`. If true it uses `shouldUpdate` and a `shallowEqual` on the flags to restrict a re-render based on them. I am still not too sure about the solution nor about the performance improvement.

**Comment by tdeekens** [comment]
Release: https://github.com/tdeekens/flopflip/releases/tag/%40flopflip%2Freact-redux%404.1.4
Docs: https://github.com/tdeekens/flopflip#injectfeaturetogglesflagnames-arraystring-propkey-string-shallowlycompareflags-boolean

If this is not working for you I'd encourage you do go into the depths of this problem and PR a tested solution.
