### ISSUE TITLE
@flipflop/react-redux doesnt exist

### ISSUE THREAD

**Issue by th3fallen** [tdeekens/flopflip#86]
am i blind or does that package not exist on npm?

**Comment by tdeekens** [comment]
Here it is: https://www.npmjs.com/package/@flopflip/react-redux.

Not sure what went wrong here.

**Comment by th3fallen** [comment]
🤦‍♂️ i typed @flipflip...

**Comment by tdeekens** [comment]
Haha, yeah the name has caused some confusion. Sorry about that. Flipflop as per "on of" was already taken hence the flip. Whoops.
