### ISSUE TITLE
App crashes in Firefox when using react-broadcast with the localstorage adapter

### ISSUE THREAD

**Issue by simon360** [tdeekens/flopflip#868]
**Describe the bug**
When using the `react-broadcast` package with `localstorage-adapter` and using Firefox, React detects an infinite re-render and crashes the app.

**To Reproduce**

1. Given the demo app in the `flopflip` monorepo
2. Replace the import of `@flopflip/react-redux` with `@flopflip/react-broadcast`
3. Run `npm start`
4. Open the page in Firefox
4. Open the web inspector console, type `updateFlags({"incrementSync": true})`, and press enter

**Expected behavior**
The increment button appears on the screen

**Actual behavior**
The app will crash, with the following message (see screenshot for more details):
```
Error: "Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops."
```

**Screenshots**
![Screenshot from 2019-11-23 14-43-42](https://user-images.githubusercontent.com/816203/69480560-58279780-0e00-11ea-9148-a7764aefb0b2.png)

**Additional context**
Tested using Firefox 70 on multiple machines (Linux and macOS). Appears to work fine on Chromium 77 on Linux.

I've tried this on three separate React apps: the app I was planning to use `flopflip` on, followed by a bare-bones app I made using `create-react-app`, before finally reproducing the bug using the demo app for `flopflip`.

It seems to be an issue _specifically_ with the combination of `localstorage-adapter` and `react-broadcast`. `localstorage-adapter` works fine with `react-redux`, and `launchdarkly-adapter` works fine with `react-broadcast`, but `localstorage-adapter` with `react-broadcast` causes the app to crash.

After testing in Chromium, I also noticed that nothing is getting saved to local storage, even though the button appears. Not sure if that's expected behaviour - I simply haven't looked into it yet, because the first issue is more pressing to me.

**Comment by tdeekens** [comment]
Thanks for looking into it and reporting the bug. I will dig deeper. I myself don't use all adapters in projects so it's sometimes a bit hard to keep track.

**Comment by tdeekens** [comment]
So I tried to reproduce in Chrome, Firefox and Firefox Developer Edition and sadly fail to.

I also pushed a small commit to the demo app to `master`. I just haven't had much time to polish it and always wanted to build a nice website instead.

I see this now

<img width="357" alt="CleanShot 2019-11-23 at 16 47 02@2x" src="https://user-images.githubusercontent.com/1877073/69481405-5c0fe580-0e11-11ea-8b59-8991f67de239.png">

You mentioned that it's only localstorage-adapter so I will focus on that now. We are using the launchdarkly-adapter for about 2 years now heavily in production applications.

Also to answer your question: the localstorage-adapter will only write to localstorage when flags actually change. I presume you haven't called `window.updateFlags({ decrementAsync: false })`. Given you would do so the adapter would persist this. Without the default flags remain applied which do not need to be persisted to localstorage.

I will get back to you once I find more.

**Comment by tdeekens** [comment]
Okay found the underlying issue and made an attempt to fix it. It's a bit odd that Firefox crashes and no other browsers or the other way round.

```txt
Successfully published:
 - @flopflip/launchdarkly-adapter@2.9.3
 - @flopflip/localstorage-adapter@1.3.2
 - @flopflip/memory-adapter@1.4.2
 - @flopflip/react-broadcast@9.1.2
 - @flopflip/react-redux@9.1.2
 - @flopflip/react@8.1.2
 - @flopflip/splitio-adapter@1.5.2
```

Please verify things and close the issue if things work for you now. Thanks again for reporting.

**Comment by simon360** [comment]
Amazing - it's working now! Thanks for picking this up so quickly!

**Comment by simon360** [comment]
Also, yup, confirmed that it's persisting to local storage. I just hadn't quite figured out how it worked yet, but I can jump around pages/reload/etc. and have the flags restored. Perfect!
