### ISSUE TITLE
Refactor `Configure` in `react` package to not use `componentWillReceiveProps`

### ISSUE THREAD

**Issue by tdeekens** [tdeekens/flopflip#907]
> The `Configure` component in `packages/react` uses `UNSAFE__componentWillReceiveProps` to update and sync the adapter upon prop changes.

By refactoring the component we should be able to change it to a Function Component from a Class Component while using hooks over lifecycle methods.

This change will get a bit hairy as code needs to move a lot and tests are coupled to lifecycle methods and need to be changed to react-testing-library.

**Comment by emmenko** [comment]
Do you want to do the refactoring of both the implementation and the tests together, or first refactor the tests and then the implementation?

**Comment by tdeekens** [comment]
First tests and then implementation woudl be very nice. Something things are quite hard to test I think. I am not sure when I'll jump at it. Spend half the last nite on the last release. Want/have to tame myself to not freak out 😄
