### ISSUE TITLE
useFeatureToggles not exported in @flopflip/react-broadcast@10.0.0

### ISSUE THREAD

**Issue by wpwood** [tdeekens/flopflip#921]
**Describe the bug**
I installed @flopflip/react-broadcast 10.0.0 via `yarn add @flopflip/react-broadcast@^10.0.0` and tried to use `useFeatureToggles` in a react app, but it does not appear to exist. It's not listed in the node_modules/@flopflip/react-broadcast/dist/typings/hooks directory, although use-feature-toggle is.

I verified that the node_modules/@flopflip/react-broadcast/package.json showed 10.0.0 as the version. It just looks like the `useFeatureToggles` hook was not included in the package.

**To Reproduce**
`yarn add @flopflip/react-broadcast@^10.0.0` or `yarn upgrade @flopflip/react-broadcast@^10.0.0` in an existing project, then attempt to 

```
import { useFeatureToggles } from '@flopflip/react-broadcast'
```

and receive an error that `useFeatureToggles` is not found

**Expected behavior**
Expect it to be found

**Screenshots**

**Additional context**
The project where I'm seeing this is a create-react-app project using TypeScript. I can use `useFeatureToggle`, no problem, so it appears to just be an issue with the npm package.

**Comment by tdeekens** [comment]
Thanks for reporting and using a hook just two days after I merged it 😄. In short: it wasn't part of v10 and is just lingering on master. Would you like to use it now? Then I could cut a release. Otherwise I'd release it in a week or two.

**Comment by wpwood** [comment]
Ah, gotcha. It's in the README, which is why I was confused. It would be useful, but I can live without it for a few weeks.

Thanks for the quick reply!

**Comment by tdeekens** [comment]
Did some work tonite. Here we go

Successfully published:
 - @flopflip/react-broadcast@10.1.0
 - @flopflip/react-redux@10.1.0
 - @flopflip/react@9.1.0

Contains use-feature-toggles in both packages.

**Comment by wpwood** [comment]
> Did some work tonite. Here we go
> 
> Successfully published:
> 
> * @flopflip/react-broadcast@10.1.0
> * @flopflip/react-redux@10.1.0
> * @flopflip/react@9.1.0
> 
> Contains use-feature-toggles in both packages.

Awesome! Thanks so much.
