### ISSUE TITLE
Bindings for Reason 🤓

### ISSUE THREAD

**Issue by emmenko** [tdeekens/flopflip#94]
Since I'm in "Reason-mode" those days, would you be interested in providing some Reason bindings? 😄

**Comment by tdeekens** [comment]
Sure. Go ahead. I am adding flow-type based checking (in #93) as it felt a couple of too many steps rewriting it all to reason compiling it though BuckleScript to JS.

Obviously I am also interested in some `*.d.ts` files. Anyway. I don't think it will help too many people but if it helps satisfying our curiosity, I am all for it.

**Comment by tdeekens** [comment]
BTW: If you find API weirdnesses: let me know. I am always down to improve the API (even if through breaking changes). Specially typed languages might help here a lot. At least that's what I hope.

**Comment by emmenko** [comment]
Yeah no rush. Also, it's not intended to "replace" anything, it just adds bindings to the existing packages so you can use it in Reason-land. It's going to be its own packages (e.g. `reason-flopflip` or something like this).
I also think Flow is perfectly fine for this library 👍

Anyway, we can also do it together if you are interested to Reason, just need to find the appropriate time 😉

**Comment by tdeekens** [comment]
Also as this library mostly serves as a little playground for us I am happy.
