### ISSUE TITLE
Ability to pass attributes to SpiltIO adapter

### ISSUE THREAD

**Issue by jeffreyffs** [tdeekens/flopflip#942]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to pass custom attributes to the SplitIO Adapter so I can configure my feature flags based on those custom attributes (ie: user platform (ios/android/web)).

see: https://help.split.io/hc/en-us/articles/360020448791-JavaScript-SDK#attribute-syntax

**Describe the solution you'd like**
I believe we would need to update the SplitioAdapterArgs type, save the new adapter args into adapter state somewhere around [here](https://github.com/tdeekens/flopflip/blob/master/packages/splitio-adapter/modules/adapter/adapter.ts#L191)

and then pass it into `getTreatments` [here](https://github.com/tdeekens/flopflip/blob/master/packages/splitio-adapter/modules/adapter/adapter.ts#L89) and [here](https://github.com/tdeekens/flopflip/blob/master/packages/splitio-adapter/modules/adapter/adapter.ts#L141)

**Describe alternatives you've considered**
Not many alternatives, the attributes have to get into the `getTreatments` call some how :)

If the above makes sense, I can take a stab at making a PR

**Comment by tdeekens** [comment]
Thanks for reporting. That sounds about right. The adapters differ a bit as to where the underlying SDK expects the user attributes. I actually do not use splitio myself. The adapter is a community maintained addition. Having said that: would you take a shot at a PR?

**Comment by jeffreyffs** [comment]
Sounds good. I'll take a poke at it sometime this week :)

**Comment by jeffreyffs** [comment]
Tested this out today and it works great. Thanks!

**Comment by tdeekens** [comment]
Cool thanks for letting me know. Lots of other small improvements went out with the last release 🤖
