### ISSUE TITLE
<ToggleFeature> is typed as React.Component<any>

### ISSUE THREAD

**Issue by jeffreyffs** [tdeekens/flopflip#953]
**Describe the bug**
Trying to use the ToggleFeature component with Typescript results in a React component with *any* for props (which results in not being able to see what props the component accepts).

**To Reproduce**
1) Import *ToggleFeature* in a tsx file
2) Try to render it.

**Expected behavior**
It should have expected typings.

**Screenshots**

![Screen Shot 2020-01-20 at 9 58 35 AM](https://user-images.githubusercontent.com/1441462/72748282-a7254b00-3b6b-11ea-9cdf-3ed0836837b3.png)

**Additional context**
It may already be solved on `master` or with some of the new refactor tickets, but I thought it might be useful to track it.

**Comment by tdeekens** [comment]
Thanks for sharing. As you noted this might we solved in master already. Might habe gotten lossed in the previous HoC party. Now with hooks typing comes more natural or is just simpler.
