### ISSUE TITLE
ConfigureFlopflip causes act error warnings in test environment

### ISSUE THREAD

**Issue by emmenko** [tdeekens/flopflip#982]
**Describe the bug**
It seems that `<ConfigureFlopflip>` still triggers state updates, causing `act` error warnings when running tests.

**To Reproduce**
See https://github.com/commercetools/merchant-center-application-kit/pull/1340

**Expected behavior**
No `act` warnings when running tests

**Comment by tdeekens** [comment]
Yup. Saw that too. I am a bit clueless now as I am not sure what more the library can do. Any help would be appreciated. I may also just not see the simple solution anymore after fiddling on it for hours.

**Comment by emmenko** [comment]
Yeah I took a look already but haven't had any luck so far. I'll keep looking into it.

**Comment by tdeekens** [comment]
Awesöme. Thanks. 

I think we/I/you somehow would obviously need:

1. Add the CI env and a throwing logger
2. A repro case. Maybe with a Promise.all rendering 25 times a TestComponent yolo style.

**Comment by tdeekens** [comment]
Okay 1. should be covered https://github.com/tdeekens/flopflip/pull/983

**Comment by tdeekens** [comment]
For the 2nd cases I started of silly to reproduce but failed due to obvious reasons and have to 🏃 now.

```js
describe('when rendering multiple configure components', () => {
  it('should not throw an act warning', () => {
    Array.from(Array(10).keys()).forEach(async () => {
      const rendered = render(<TestComponent />);

      await rendered.waitUntilReady();

      expect(rendered.queryByText('Is enabled: Yes')).toBeInTheDocument();
    });
  });
});
```

**Comment by emmenko** [comment]
I found an interesting discovery: the simplest test possible, the first time rendering within the `it`, the second time rendering in a `beforeEach`. The second time is where the warning error is thrown.

<img width="1306" alt="Screenshot 2020-02-15 at 17 49 03" src="https://user-images.githubusercontent.com/1110551/74591838-a02f1280-501b-11ea-9d1f-2fe232a855f6.png">

<img width="1309" alt="Screenshot 2020-02-15 at 17 49 35" src="https://user-images.githubusercontent.com/1110551/74591852-c3f25880-501b-11ea-9206-511c9549e011.png">

**Comment by emmenko** [comment]
I also created a CodeSandbox but the warning doesn't pop there:

https://codesandbox.io/s/flopflip-configure-state-updates-px2rv

**Comment by tdeekens** [comment]
Oh super nice! Still confused why though. When and how often does a beforeEach run? Strange also that the CodeSandbox does not throw it. These test cases are super nice for the library - solved or not 🦐.

**Comment by emmenko** [comment]
I'm starting to think that the implementation of `<Configure>` is just fine and the problem relies on using `beforeEach`.
I also found an article by Kent saying that he also does not like using those hooks.

<img width="828" alt="image" src="https://user-images.githubusercontent.com/1110551/74594056-3cfcaa80-5032-11ea-8f44-36fa8bb8bab2.png">

https://kentcdodds.com/blog/test-isolation-with-react

I actually agree with that and can also relate as I bumped into similar issues when I was refactoring/fixing tests in the MC, as we used to do that previously with enzyme. Getting rid of using `beforeEach` or nested describes solved most of the issues.

I would say that we should just write our tests in a more "isolated" way. I'll try that in appkit and see if it solves the issues.

**Comment by tdeekens** [comment]
Thanks for digging deeper. I agree that beforeEach can often just be achieved with „smarter“ ways of using render-fns/helpers and that it usually eases things. 

Still wondering what actually is so strange on a beforeEach and why it works so „different“ from how one could hope and when similar edge cases exist without flopflip specifically. As you said they exist. Just wondering what specifically triggers them. 

I right now also don’t think flopflip can do much immediately. Maybe I can play around a bit more at some point as we have a repro case.

**Comment by emmenko** [comment]
Another interesting discovery. Even without `beforeEach`, this test still throws the warnings:

```jsx
describe('without `projectKey`', () => {
  it('should redirect to the root', () => {
    const rendered = renderApp(<BackToProject />);
    fireEvent.click(rendered.getByText('Back to project'));
    expect(mocked(window.location.replace)).toHaveBeenCalledWith('/');
  });
});
```

The test is not marked as `async` though, and it actually makes sense to **wait** after clicking on something. When we do that, the warning is gone:

```jsx
describe('without `projectKey`', () => {
  it('should redirect to the root', async () => {
    const rendered = renderApp(<BackToProject />);
    fireEvent.click(rendered.getByText('Back to project'));
    await wait(() => {
      expect(mocked(window.location.replace)).toHaveBeenCalledWith('/');
    });
  });
});
```

**Comment by tdeekens** [comment]
Is this error triggered by flopflip itself? If, I presume it assumes it is still mounted, updates state while another update is not awaited? It's just interesting that these cases come up with useEffect not with Class Component lifecycle methods. Maybe there act isn't actually warning that strictly?

**Comment by emmenko** [comment]
I think it's due to the usage of functional components with hooks and the async behavior. And given that this behavior resembles more the real usage, it just shows that our tests setup has been "incorrect and fragile" this all time.

**Comment by tdeekens** [comment]
I also tried to follow along with the `useMutableSource` stuff the last weeks. It's kind of maybe around this. Maybe not.

Do you want to keep this open or closeit?

**Comment by charliedavison** [comment]
@tdeekens Its been a while since this was closed but I'm having the same issue - is there a known way to resolve this now?
